books/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from .views import AuthorViewSet, BookViewSet, CommentViewSet


router = DefaultRouter()
router.register('authors', AuthorViewSet)
router.register('books', BookViewSet, basename='books')
router.register(r'books/(?P<book_id>\d+)/comments', CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path(
        'redoc/',
        TemplateView.as_view(template_name='redoc.html'),
        name='redoc'
    ),
]

books/books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("users.urls")),
    path("api/", include("api.urls"))
]

books/main/urls.py
from django.urls import path

from .views import AuthorBookListView, BookListView, BookDetailView, SearchView


app_name = 'main'


urlpatterns = [
    path('', BookListView.as_view(), name='books_list'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='books_detail'),
    path('author/<str:username>/', AuthorBookListView.as_view(), name='author_books'),
    path('search/', SearchView.as_view(), name='search_books')
]

books/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
)
from django.urls import path

from .views import SignUp


app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    )
]

books/main/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'text',
        )


class SearchForm(forms.Form):
    query = forms.CharField(
        max_length=128
    )

    class Meta:
        fields = (
            'query',
        )

books/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
<style>
    a {text-decoration: none;}
    li {list-style-type: none;}
</style>
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'main:books_list' %}" class="nav-link px-2 text-secondary">Главная</a></li>
        </ul>

        <form action="{% url 'main:search_books'%}" method="post" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            {%csrf_token%}
          <input id="id_query" name="query" type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
            {% if request.user.is_authenticated %}
                <a href="{% url 'users:logout' %}" class="btn btn-outline-light me-2">Logout ({{request.user.username}})</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2">Login</a>
                <a href="{% url 'users:signup' %}" class="btn btn-warning">Sign-up</a>
            {% endif %}
        </div>
      </div>
    </div>
  </header>
    <div class="container-md">
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

books/templates/redoc.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>ReDoc</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url="{% static 'schema.yaml' %}"></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js"> </script>
  </body>
</html>