books/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from .views import AuthorViewSet, BookViewSet, CommentViewSet


router = DefaultRouter()
router.register('authors', AuthorViewSet)
router.register('books', BookViewSet, basename='books')
router.register(r'books/(?P<book_id>\d+)/comments', CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path(
        'redoc/',
        TemplateView.as_view(template_name='redoc.html'),
        name='redoc'
    ),
]

books/books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("users.urls")),
    path("api/", include("api.urls"))
]

books/main/urls.py
from django.urls import path

from .views import AuthorBookListView, BookListView, BookDetailView, SearchView


app_name = 'main'


urlpatterns = [
    path('', BookListView.as_view(), name='books_list'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='books_detail'),
    path('author/<str:username>/', AuthorBookListView.as_view(), name='author_books'),
    path('search/', SearchView.as_view(), name='search_books')
]

books/main/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator


User = get_user_model()


class Book(models.Model):
    """ Модель книги """

    name = models.CharField(
        max_length=128,
        verbose_name='Название',
        unique=True
    )
    published_at = models.PositiveIntegerField(
        verbose_name='Год издания',
        validators=[
            MaxValueValidator(
                datetime.now().year,
                'Год издания не может превышать текущий!')
        ]
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    authors = models.ManyToManyField(
        to=User,
        related_name='books',
        verbose_name='Автор(ы)'
    )
    is_achieved = models.BooleanField(
        default=False,
        verbose_name='Книга в архиве?'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'


class Comment(models.Model):
    """ Модель комментария """

    text = models.TextField(
        verbose_name='Текст комментария'
    )
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    book = models.ForeignKey(
        to=Book,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Книга'
    )
    published_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата и время создания/изменения'
    )

    def __str__(self):
        return f'{self.book}|{self.author}'

    class Meta:
        ordering = ['-published_at']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

books/main/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'text',
        )


class SearchForm(forms.Form):
    query = forms.CharField(
        max_length=128
    )

    class Meta:
        fields = (
            'query',
        )

books/main/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, View
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import CommentForm, SearchForm
from .models import Book
from .mixins import ArchivedBookMixin


User = get_user_model()


class AuthorBookListView(ListView):
    model = User
    template_name = 'main/index.html'
    context_object_name = 'books'

    def get_queryset(self):
        username = self.kwargs.get('username')
        return super().get_queryset().filter(username=username).first().books.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        context['title'] = f'Книги {author.username}'
        return context


class BookListView(ArchivedBookMixin, ListView):
    model = Book
    template_name = 'main/index.html'
    context_object_name = 'books'
    search_form = SearchForm


class BookDetailView(ArchivedBookMixin, DetailView):
    model = Book
    context_object_name = 'book'
    search_form = SearchForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated and self.request.method == 'POST':
            return HttpResponseRedirect(reverse('users:login'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(data=request.POST or None)
        if form.is_valid():
            book = get_object_or_404(Book, pk=kwargs.get('pk'))
            new_comment = form.save(commit=False)
            new_comment.author = self.request.user
            new_comment.book = book
            new_comment.save()
            return HttpResponseRedirect(reverse(
                'main:books_detail',
                kwargs={'pk': kwargs.get('pk')}
            ))


class SearchView(ArchivedBookMixin, View):
    model = Book

    def post(self, request, *args, **kwargs):
        form = SearchForm(data=request.POST or None)
        if form.is_valid():
            books = self.get_queryset().filter(
                name__icontains=form.cleaned_data.get('query')
            )
            return render(
                request,
                'main/index.html',
                {
                    'books': books,
                    'title': 'Поиск',
                    'search_form': form
                }
            )

books/templates/main/book_detail.html
{% extends 'base.html' %}
{% block title %}
    {{title}}
{% endblock %}

{% block content %}
    <div class="col-md-12 text-center">
        <h3>{{book}}</h3>
        <div class="row">
            <div class="col-md-6">
                {{book.description}}
            </div>
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Комментарии
                    </div>
                    <div class="panel-body comments">
                        <form action="{% url 'main:books_detail' pk=book.id %}" method="POST">
                            {%csrf_token%}
                            <textarea name="text" class="form-control" placeholder="Оставьте Ваш комментарий" rows="5"></textarea>
                             <br>
                            <input type="submit" class="btn btn-success btn-block" value="Отправить">
                            <hr>
                        </form>
                        <ul class="media-list">
                            {% for comment in book.comments.all %}
                                <li class="media">
                                    <div class="comment">
                                        <div class="media-body">
                                            <strong class="text-success">{{comment.author}}</strong>
                                            <span class="text-muted">
                                                <small class="text-muted">{{comment.published_at|date:"H:i, d-m-Y"}}</small>
                                            </span>
                                            <p>
                                                {{comment.text}}
                                            </p>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

books/templates/main/index.html
{% extends 'base.html' %}
{% block title %}
{{title}}
{% endblock %}
{% block content %}
{% for book in books %}
<div class="col-md-6 d-flex justify-content-center">
    <div class="card m-1" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title text-center">
                <a href="{% url 'main:books_detail' pk=book.id %}">{{book.name}}</a>
            </h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">
                {% for author in book.authors.all %}
                    {% if not forloop.last %}
                        <a class="link-secondary" href="{% url 'main:author_books' username=author.username%}">{{author}},</a>
                    {% else %}
                        <a class="link-secondary" href="{% url 'main:author_books' username=author.username%}">{{author}}.</a>
                    {% endif %}
                {% endfor %}
            </h6>
            <p class="card-text">{{book.description|truncatewords:15}}</p>
        </div>
        <div class="card-footer text-muted">
            Количество комментариев: {{book.comments.count}}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}